apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon
spec:
  selector:
    matchLabels:
      name: nignx-daemon
  template:
    metadata:
      labels:
        name: nignx-daemon
    spec:
      containers:
        - name: nignx
          image: nginx