apiVersion: apps/v1
kind: Deployment
metadata:
    name: mosquitto-app
    labels:
      app: mosquitto
spec:
    replicas: 1
    selector:
      matchLabels:
        app: mosquitto
    template:
      metadata:
        labels:
          app: mosquitto
      spec:
        containers:
          - name: mosquitto
            image: eclipse-mosquitto
            ports:
              - containerPort: 1883
            volumeMounts:
              - name: mosquittos-config
                mountPath: /mosquitto/config
              - name : mosquitto-secret
                mountPath: /mosquitto/secret
        volumes:
          - name: mosquittos-config
            configMap:
              name: mosquitto-config-file
          - name: mosquitto-secret
            secret:
              secretName: mosquitto-secret