apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
spec:
  type: LoadBalancer
  selector:
    app: guestbook
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  