apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: php-redis
          image: gcr.io/google_samples/gb-frontend:v5
          env:
            - name: GET_HOSTS_FROM
              valueFrom:
                configMapKeyRef:
                    name: redis-config
                    key: GET_HOSTS_FROM
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80